// "use client";

import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "./theme";

import "./globals.css";
import "@/styles/style.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}

// import React, { useEffect, useState } from "react";
// import Loader from "@/components/common/Loader/Loader.component";

// import "jsvectormap/dist/jsvectormap.css";
// import "flatpickr/dist/flatpickr.min.css";
// import "@/styles/satoshi.css";
// import "@/styles/style.css";
// import "@/styles/global.scss";
// // import "./globals.scss";

// export default function RootLayout({ children }) {
//   const [sidebarOpen, setSidebarOpen] = useState(false);
//   const [loading, setLoading] = useState(true);

//   // const pathname = usePathname();

//   useEffect(() => {
//     setTimeout(() => setLoading(false), 1000);
//   }, []);

//   return (
//     <html lang="en">
//       <body suppressHydrationWarning={true}>
//         <ThemeProvider theme={theme}>
//           <CssBaseline />
//           <div className="dark:bg-boxdark-2 dark:text-bodydark">
//             {loading ? <Loader /> : children}
//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
